### ISSUE TITLE
Update QLFS pipeline to extract data from EDD

### ISSUE THREAD

**Issue by taz-chiles** [open-innovations/yff-data#100]
We currently pull datasets from a URL in our extract.py scripts for YFF economics pipelines, however this is fragile and unreliable. We should instead start to pull data from EDD - where Christian has kindly prepared the data in CSV format.

Initially, we will look at pulling vacancies data in this way - with a view to updating other pipelines.

[ ] cd working directory
[ ] Run dvc import -url with the following urls followed by the filename

https://github.com/economic-analytics/edd/blob/main/data/csv/LMS_variable_lookup.csv

https://github.com/economic-analytics/edd/blob/main/data/csv/LMS_data.csv

This will download a ~.csv.dvc file into the working directory. This will be updated when the source updates and replaces the extract scripts we currently have in place.

[ ] Transform the data in to the data direcory
[ ] Prepare the data for visualisation from the data direclty into the src/_data directory.

**Comment by gilesdring** [comment]
I may have started this! Need to check!

**Comment by luke-strange** [comment]
Moving to in review as I think this has been done. We can probably also delete `scripts/qlfs` as its not longer used.

**Comment by gilesdring** [comment]
The one part still being used was the date / time. I've generalised this and converted the prepare script to jupyter.

Closed now
