### ISSUE TITLE
Update NEET pipeline to extract data from EDD

### ISSUE THREAD

**Issue by taz-chiles** [open-innovations/yff-data#101]
We currently pull datasets from a URL in our extract.py scripts for YFF economics pipelines, however this is fragile and unreliable. We should instead start to pull data from EDD - where Christian has kindly prepared the data in CSV format.

Initially, we will look at pulling vacancies data in this way - with a view to updating other pipelines.

[ ] cd working directory
[ ] Run dvc import -url with the following urls followed by the filename

https://github.com/economic-analytics/edd/blob/main/data/csv/LMS_variable_lookup.csv

https://github.com/economic-analytics/edd/blob/main/data/csv/LMS_data.csv

This will download a ~.csv.dvc file into the working directory. This will be updated when the source updates and replaces the extract scripts we currently have in place.

[ ] Transform the data in to the data direcory
[ ] Prepare the data for visualisation from the data direclty into the src/_data directory.

**Comment by gilesdring** [comment]
Data is already available in `working/LMS_data.csv`. Checking the variable names

**Comment by gilesdring** [comment]
Methodoloy is here

https://www.ons.gov.uk/employmentandlabourmarket/peoplenotinwork/unemployment/methodologies/youngpeoplenotineducationemploymentortrainingneetukmethodologymay2022

**Comment by gilesdring** [comment]
Have now moved processing for NEET to pipelines repo. Closing this ticket.
