### ISSUE TITLE
Implement automatic ticks with yaml files.

### ISSUE THREAD

**Issue by luke-strange** [open-innovations/yff-data#103]
From @gilesdring :

I think the simplest / quickest way to achieve this is to modify the visualisations.yaml file, based on the following code:

```python
import yaml

# Read config from file
with open(path_to_file) as f:
  viz = yaml.safe_load(f.read())

# Update the viz definition
print(viz[1]['config']['axis']['x']['max']) # prints current value
viz[1]['config']['axis']['x']['max'] = 40
print(viz[1]['config']['axis']['x']['max']) # prints 40

# Write config to file
with open(path_to_file, 'w') as f:
  f.write(yaml.dump(
    viz,
    default_flow_style=False
  ))
```

**Comment by luke-strange** [comment]
I'd like to check if this works as intended when the data is updated, and if completed successfully I can make tickets to implement this on the other pages of the dashboard.

**Comment by ODILMichelle** [comment]
Is this complete @luke-strange? Been closing a few items which appear to have been left open and wasn't sure about this..
