### ISSUE TITLE
Write blog post about Phase 2 work

### ISSUE THREAD

**Issue by ODILMichelle** [open-innovations/yff-data#104]
Describe what we're aiming to do with this phase - most of this exists in scoping documents from Phase 2A.

**Comment by ODILMichelle** [comment]
@taz-chiles one for you perhaps?

**Comment by taz-chiles** [comment]
@ODILMichelle Sure, happy to pick this up along with the hub page amendments on #105 - will think about a rough outline then will  pick up next week :)

**Comment by ODILMichelle** [comment]
Works perfectly, thanks Taz.

**Comment by ODILMichelle** [comment]
Made some comments, @taz-chiles is looking at this now.

**Comment by taz-chiles** [comment]
Second draft in the blog editor - comments welcome https://open-innovations.org/blog/edit/preview?id=00013

**Comment by ODILMichelle** [comment]
Think this is done, and can be closed?

**Comment by taz-chiles** [comment]
Excellent! Closing :)
