### ISSUE TITLE
Update content on YFF hub page

### ISSUE THREAD

**Issue by ODILMichelle** [open-innovations/yff-data#105]
Ensure we add in Phase 2 context.

**Comment by ODILMichelle** [comment]
@taz-chiles is this something you can look at as well please, if you have enough capacity over the next week or so?

**Comment by taz-chiles** [comment]
Hub page has been updated with the new blog post and I will add the interview with Chris as this is released. 

@ODILMichelle @gilesdring let me know of any amendments

**Comment by ODILMichelle** [comment]
I think this is done, thanks! As such, can be closed...

**Comment by taz-chiles** [comment]
Excellent! Will close as completed :)
