### ISSUE TITLE
Link pipeline docs pages for QLFS and NEET to main page

### ISSUE THREAD

**Issue by gilesdring** [open-innovations/yff-data#109]

**Comment by ODILMichelle** [comment]
@gilesdring is this ready? Anything else needed to get it into doable?

**Comment by gilesdring** [comment]
Have added links to any dashboard page that has `<dashboard url>/pipeline/` defined.

Currently works for labour market and neet

Simple wording - can be updated in https://github.com/open-innovations/yff-data/blob/main/src/_includes/layouts/dashboard.njk

**Comment by gilesdring** [comment]
@ODILMichelle Look OK to you?

**Comment by ODILMichelle** [comment]
Looks grand.
