### ISSUE TITLE
Update QLFS charts derived from A06

### ISSUE THREAD

**Issue by gilesdring** [open-innovations/yff-data#114]
Rename __Overall unemployment rate & Economic Inactivity__ to __Labour market status__

Three series on the same chart 16-24:
* Overall unemployment rate 16-24
* Economic Inactivity 16-24
* Employed 16-24

Focus on 3 years for the time being (Andrea to look whether we want longer time series as well)

Two tabs
* Young people not in FTE 
* Young people in FTE

**Comment by taz-chiles** [comment]
Visualisations added as described above, let me know if any comments

https://data.youthfuturesfoundation.org/dashboard/labour-market/

**Comment by ODILMichelle** [comment]
Will need to amend the hover tooltip label inline with any decisions made in response to https://github.com/open-innovations/yff-data/issues/112#issuecomment-1557277451

**Comment by ODILMichelle** [comment]
Above comments seem to be resolved now. Suggest closing it, if you are happy with it @taz-chiles
