### ISSUE TITLE
Update headline stats with date of last extract

### ISSUE THREAD

**Issue by taz-chiles** [open-innovations/yff-data#119]
Include a footnote/some text within the headline component to show the date of last data extract. 
Should read 'as of XX/XX/XX' - see Leeds 2023 panels

- [x] QLFS 
- [x] CPI
- [x] NEET
- [x] Homepage

**Comment by ODILMichelle** [comment]
@taz-chiles, I will pick up Labour Market Stats as part of an overall review of both pages as I can basically copy and paste the NEET code.

Won't be able to pick up CPI or Homepage at this point in time.

**Comment by ODILMichelle** [comment]
Scratch that, I won't do this - please take it on @taz-chiles !
