### ISSUE TITLE
Create initial data files for CFF page

### ISSUE THREAD

**Issue by gilesdring** [open-innovations/yff-data#12]
Create `_data` directory & files in the `reports/cff` directory.

Data files to capture information about applications to CFF programme, the cohort etc.

27 Mar MB note - Scope for this page has changed slightly now. We are no longer showing applications, or those short-listed (as per email on 24 Mar), and will instead share some information about eligibility criteria and areas eligible to apply.

**Comment by gilesdring** [comment]
Pre-requisites

- [ ] Collate existing information sent to us about CFF

**Comment by taz-chiles** [comment]
I have started adding data files for the CFF page into the `_data/sources/cff` directory in the same way we did for phase 1 reports. 

I'll be adding more data files as I build out the CFF project page as in #14 - do we need to keep both tickets open @gilesdring ?

**Comment by taz-chiles** [comment]
Closing this as done - we have built the page and fed back to the client, so will open new tickets for any further amendments to this page.
