### ISSUE TITLE
Update NEET data tables

### ISSUE THREAD

**Issue by taz-chiles** [open-innovations/yff-data#120]
Table should have 3 tabs: 
- All
- Men
- Women

Each table with three columns showing overall rates, unemployment and economic inactivity. 

- Clean up column headings, dates and reduce number of decimal places

**Comment by ODILMichelle** [comment]
Is this ready @taz-chiles?

**Comment by gilesdring** [comment]
First pass at this done.

Currently only have total NEET as a rate. Have put in levels for total, unemployed and economically inactive.

https://data.youthfuturesfoundation.org/dashboard/neet/

![Image](https://github.com/open-innovations/yff-data/assets/1731108/ba2e259f-0dc0-4e02-b828-f95084d1381c)

**Comment by ODILMichelle** [comment]
Made same comment on #128 but adding it here for completeness, and they are linked and we need to make decision for both. @gilesdring & @taz-chiles could you discuss and agree these?

- Is there stylistic best practice which says justifying values to the LHS in a table is the correct approach, even if the heading of the table is centrally justified? Both tables currently showing this & not sure what is best
- One key difference between the two tables at present is that one includes the % in line (e.g. 38.2%), the other has the % in the top.
- Another key difference is how we're indicating the quarters in each of these e.g. the above uses 22-07-01, whereas the NEET stats use e.g. July-Sept 2022. Feels like we should be using the same approach on these (to my mind, written data format such as July-Sept 2022 is more human readable)

**Comment by gilesdring** [comment]
Saw other comments and had already tweaked locally. I think RHS justification better. Have also fixed column widths.

**Comment by gilesdring** [comment]
%-age should be in each cell, and date forma should be per NEET - have already discussed with @taz-chiles. Consequently closing this ticket.
