### ISSUE TITLE
Add time series of CPI change over 10 years

### ISSUE THREAD

**Issue by taz-chiles** [open-innovations/yff-data#121]
A time series chart going back 10 years that shows the change in rate of the current 4 categories (to be added as second tab on the existing visualisation on this page).

This was the data source shared by YFF: https://www.ons.gov.uk/economy/inflationandpriceindices/timeseries/l55o/mm23

**Comment by ODILMichelle** [comment]
What is needed to make this ready @taz-chiles?

**Comment by ODILMichelle** [comment]
I believe this is complete picked up ticket #190 to ensure we're generating words. 

There may be more to come back on this in the future, but will add new tickets if it is needed.
