### ISSUE TITLE
Add an increase/decrease indicator to the headline dashboard

### ISSUE THREAD

**Issue by taz-chiles** [open-innovations/yff-data#124]
On the headline stats for all the economics pages, we want to add an indicator (an up or down arrow will suffice) of whether the current headline figure has increased or decreased on the last figure. 

The simplest way might be to use the prefix attribute on the component with a simple unicode character/icon to indicate up or down.

**Comment by luke-strange** [comment]
@slowe I've added a prefix column in the `data/cpi/headlines.csv` file, but not showing up on the vis:



![Image](https://github.com/open-innovations/yff-data/assets/92686634/b43f785d-318d-4e95-a533-4fa882303180)

Not sure how to fix this.

**Comment by luke-strange** [comment]
![Image](https://github.com/open-innovations/yff-data/assets/92686634/e66f4ba3-f95e-4639-8304-f04cc797c958)

this is the config in `dashboard/cpi/_data/visualisations.yaml`

**Comment by slowe** [comment]
![Screenshot 2023-06-07 at 15-16-11 Consumer Prices Index - Youth Futures Foundation](https://github.com/open-innovations/yff-data/assets/299787/2692c25e-1ba6-4f72-8b6f-006c45b75f76)
To possibly reduce confusion around increase/decrease it might be an idea to have that in the note text below rather than as a prefix.

**Comment by luke-strange** [comment]
- change headline to Consumer Prices Index Percentage change
 - Fix the note to say "As at xxxx date. This has increased/decreased since last update"

**Comment by luke-strange** [comment]
Yes you're right michelle. we need to do this for other areas too. Would it be worth making separate tickets for those so we can chunk up the jobs a bit more to avoid this ticket lying around for a while.
