### ISSUE TITLE
Amend Labour Market stats data tables

### ISSUE THREAD

**Issue by ODILMichelle** [open-innovations/yff-data#128]
- [ ] Reduce number of decimal places
- [ ] Ensure column headings & what is displayed is relevant to visualisations displayed above (e.g. showing 6 and 12 month unemployment rate). Don't need to show all data going back to the start of the data set - the rolling 3 years should be fine.

**Comment by ODILMichelle** [comment]
@luke-strange @taz-chiles As the two most likely to implement this, are you happy this is understandable, or is there some nuance I've missed?

**Comment by taz-chiles** [comment]
I have updated the tables as below: 


![Image](https://github.com/open-innovations/yff-data/assets/97239140/c093ea64-ab7d-4f07-94c7-99530724972b)



![Image](https://github.com/open-innovations/yff-data/assets/97239140/6636cd2d-3c06-4ec0-9501-b132747e3259)



![Image](https://github.com/open-innovations/yff-data/assets/97239140/0eb6ae9c-4315-4df6-973e-59fb0d3c693e)




![Image](https://github.com/open-innovations/yff-data/assets/97239140/5307af33-a65b-4c3f-a7f9-aa64505ead6d)

**Comment by ODILMichelle** [comment]
For the second tab, should it be unemployed for over 6 months, or unemployed for 6-12 months?

For all, should we be adding a .0 to the end of whole numbers? e.g. first column of the top image, for quarter 2020-07-01 says 17, rather than 17.0


And I'll make the same comments on #120 as they are linked and we need to make decision for both. @gilesdring & @taz-chiles could you discuss and agree these?

- Is there stylistic best practice which says justifying values to the LHS in a table is the correct approach, even if the heading of the table is centrally justified? Both tables currently showing this & not sure what is best
- There is a key difference between the two tables at present - one includes the % in line (e.g. 38.2%), the other has the % in the top.

**Comment by ODILMichelle** [comment]
Oh, and another point (sorry!), we will want column widths on each tab to be the same if possible, to reduce cognitive load for people when clicking between these (at present there is a jump between the first two and second two tabs)

**Comment by gilesdring** [comment]
Have aligned this with NEET tables. Could you take another look @ODILMichelle, then close if looks OK.

**Comment by gilesdring** [comment]
Feels like we might need a footer on the bottom, which could help. I'll take a look. May be a separate ticket.

**Comment by ODILMichelle** [comment]
Raised a separate ticket re the jump #130. Will consider this ticket closed.
