### ISSUE TITLE
Create initial version of individual topic tag pages

### ISSUE THREAD

**Issue by gilesdring** [open-innovations/yff-data#15]

**Comment by ODILMichelle** [comment]
YFF will be in touch with named topic tag pages in the next few days.

**Comment by ODILMichelle** [comment]
From Anna: 

The topics in the Toolkit are: Wage subsidies, on-the-job training, off-the-job training (also called in some cases ‘technical and vocational education’, which we may use as an alternate), mentoring/coaching, basic skills training, life skills training, and apprenticeships. 

This list will expand over time as we add more topics, and potentially we may partly be guided towards future Toolkit topics by how the Dashboard goes.

**Notes:** 
This doesn't feel, to me anyway, like it is necessarily going to cover the range of topic tags we might wish to see for the data dashboard. Let me know your thoughts.

**Comment by gilesdring** [comment]
topic tags should be in front-matter of page, like this:

```
topic:
  - topic_1
  - topic_2
```

Topic tags should be "slugified": lower case and with spaces or non-alphanumeric characters replaced by `_`
* 
Wage subsidies
on-the-job training
off-the-job training (also called in some cases ‘technical and vocational education’, which we may use as an alternate)
mentoring/coaching, basic skills training, life skills training, and apprenticeship

**Comment by gilesdring** [comment]
Have reverted to unslugified versions of the topics. It worked better.
