### ISSUE TITLE
Remove axis & key from visualisations on data dashboard landing page

### ISSUE THREAD

**Issue by ODILMichelle** [open-innovations/yff-data#150]

**Comment by gilesdring** [comment]
Alternatively make scale-less versions labelled as 'trends' which link through to the specific graphs #177

**Comment by gilesdring** [comment]
![Image](https://user-images.githubusercontent.com/97239140/240618867-a3f22873-8c94-4f1f-9619-bfcdbd604ce5.png)

**Comment by ODILMichelle** [comment]
It certainly looks better without the axis labels I think. 

And at the risk of being a pain, it led me to wonder what the visualisation looks like with the key but without the axis labels (just to help provide some context to viewers). 

Feels like this should remain a prototype , rather than changes pushed across the site, until we speak with YFF however?

**Comment by taz-chiles** [comment]
These look great @slowe @ODILMichelle - I think no axis labels with a key looks best - then you can get an idea of overall trends before clicking onto the main page for specific figures.

**Comment by gilesdring** [comment]
Yes - I think it needs the key, unless we can pick a single variable to plot

**Comment by ODILMichelle** [comment]
I'm going to say this is complete as we have the ability to do this. We can continue ongoing discussions in #192
