### ISSUE TITLE
Update tick_gen

### ISSUE THREAD

**Issue by luke-strange** [open-innovations/yff-data#151]
Giles had a nice implementation using a while loop to iterate through tick spacing options until you get less than 5 total ticks. Want to add this to the python version.

**Comment by luke-strange** [comment]
I've done this, need to test it.

**Comment by ODILMichelle** [comment]
Can you add it to the most appropriate sprint and column please, to help us keep track of what we're all up to :)

**Comment by luke-strange** [comment]
Deployed in `scripts/cpi/vis.py` , source code in `scripts\util\util.py`.
