### ISSUE TITLE
Add Open Innovations credits to the site

### ISSUE THREAD

**Issue by luke-strange** [open-innovations/yff-data#158]
We need to check with YFF what we agreed on this (maybe we didn't discuss it).

Need to show that the site was built by OI.

Also ideally want credits on the charts when you download them (like the YFF credit below)

![Image](https://github.com/open-innovations/yff-data/assets/92686634/d40d4015-5c38-440b-bd0b-2b20ab0da706)

**Comment by ODILMichelle** [comment]
@gilesdring I know you've been working on this, is this now complete?

**Comment by gilesdring** [comment]
I think so. Implementation is footer at bottom, then for rendered images only, shows the OI credit. Had a few formatting issues, but seems OK wherever tested.
