### ISSUE TITLE
Ensure NEET link to pipeline documentation appears below headline stats

### ISSUE THREAD

**Issue by ODILMichelle** [open-innovations/yff-data#172]

**Comment by ODILMichelle** [comment]
@gilesdring is this something for you, or can one of the wider team pick it up?

**Comment by taz-chiles** [comment]
I have updated the NEET code to include named visualisations, so the headline and pipeline documentation text are now in the right place! 

@ODILMichelle can this be closed?

**Comment by ODILMichelle** [comment]
I reckon so, thanks for this! (Will leave you to get the dopamine hit :-D )
