### ISSUE TITLE
Work out what vacancy visualisations to add to data dashboard landing page

### ISSUE THREAD

**Issue by ODILMichelle** [open-innovations/yff-data#173]

**Comment by ODILMichelle** [comment]
Vacancies currently blocked by #93 and #94.

**Comment by ODILMichelle** [comment]
Regarding CPI visualisations to add to landing page, @luke-strange I was wondering what you thought might be the main visualisation to add to the data dashboard landing page (e.g. https://data.youthfuturesfoundation.org/). 

I was wondering if it is the first visualisation showing CPI changes most affecting young people? Given that was the first visualisation we were asked to create, I think it feels the best to show - thoughts?

**Comment by luke-strange** [comment]
I agree - the bar chart with categories affecting young people is most important. @ODILMichelle

**Comment by ODILMichelle** [comment]
Picked up CPI visualisation and renamed this and ticketed it as #194
