### ISSUE TITLE
Add 'Seasonally adjusted' to headings on page and remove from chart title

### ISSUE THREAD

**Issue by ODILMichelle** [open-innovations/yff-data#175]
e.g. Seasonally adjusted unemployment for young people

**Comment by taz-chiles** [comment]
Done - can be closed if no other comments

**Comment by ODILMichelle** [comment]
@taz-chiles fancy closing this?

**Comment by taz-chiles** [comment]
@ODILMichelle delighted to :) I think it could make sense to include notes on what seasonally adjusted in the methodology page, do you think? Shall I close this then and we can pick up as a separate ticket
