### ISSUE TITLE
Review employment stats page & data

### ISSUE THREAD

**Issue by ODILMichelle** [open-innovations/yff-data#176]
From YFF: 

Ordering of employment data is a bit odd, think it should be:

- Overall unemployment and inactivity (for all, not just those not in FTE). However, happy to debate that – I can see an argument that our ‘headline’ stat is those not in FTE

- Breakdowns by LTU (6-12, 12+)
- Breakdowns by FTE vs not-FTE
- Breakdowns by 16-17 vs 18-24
- Breakdowns by gender

**Comment by ODILMichelle** [comment]
Spoke with @gilesdring briefly about this, and agreed that this is multiple tickets. Will work on breaking this out now ahead of todays sprint meeting

**Comment by ODILMichelle** [comment]
Blocks #199. Once we know how to move on the above, should review whether 199 is now unblocked or obsolete

**Comment by gilesdring** [comment]
On the point about the ordering of charts in the Labour Market dashboard, we’re proposing the following:
 
* Headline figures
    * [ ] Headlines of Unemployment and Economically Inactive rate for 16-24 year olds (both regardless of FTE status).
    * [ ] Remove Long term unemployment stats from headline.
    * [ ] Thought – could add in baseline whole population Unemployment and Economically Inactive as a headline comparator?
* Long-term unemployment
    * [ ] Long-term unemployment (6-12/12+) for past 3 years and all available data (2 charts, tabbed)
* Labour Market Status (Overall / Economically inactive / in employment) by factor
    * [ ] …for 16-24 Not FTE and FTE (2 charts) – no change to current
    * [ ] …for 16-17 and 18-26 for people Not in FTE  (2 charts) – new data extract / charts
    * [ ] …for 16-24 Women and Men  (2 charts) – new data extract / charts

**Comment by gilesdring** [comment]
Related tickets

 #206

**Comment by ODILMichelle** [comment]
We've got separate tickets for other visualisations, so lets close this one off
