### ISSUE TITLE
Ensure the last tick is on the most recent data release period

### ISSUE THREAD

**Issue by ODILMichelle** [open-innovations/yff-data#178]

**Comment by gilesdring** [comment]
![Image](https://github.com/open-innovations/yff-data/assets/1731108/65a823bc-d366-40ca-ba34-f7557a9bd85b)

Autogenerated x-axis labels on charts now 'count backwards' from the most recent.

To use this, omit the `axis.x.ticks` object, per src/dashboard/labour-market/_data/visualisation/economic_activity_in_full_time_education_3_years.yml

**Comment by gilesdring** [comment]
@ODILMichelle @taz-chiles FYI

Needs a new ticket raising to make the labels better formatted - this may be built in to the YFF version of charts already.
