### ISSUE TITLE
Explore making x axis label visualisations angled

### ISSUE THREAD

**Issue by ODILMichelle** [open-innovations/yff-data#179]
Feedback from YFF that they are keen to explore

**Comment by slowe** [comment]
@ODILMichelle Why do they want it? Is it a house-style? Is it to fit more text into labels? Something else?

**Comment by ODILMichelle** [comment]
Hello! Excellent question & this was largely dumped on the board previously to work through. 

So to provide context, we don't always get a direct line to those giving feedback on YFF - and this is one of those instances. 

I think the specific challenge this is in relation to is the NEET data visualisations where the dates run into each other as we're showing 'all time' data. 
<img width="824" alt="Screenshot 2023-06-07 at 16 50 35" src="https://github.com/open-innovations/yff-data/assets/88284441/ccc32eac-e735-43c3-8028-0d50213aea27">


Somehow, we're not seeing the same congestion on the x axis for Labour Market: 
![Screenshot 2023-06-07 at 17 04 32](https://github.com/open-innovations/yff-data/assets/88284441/6cf79248-5df1-4cac-8454-07dd7380ba08)

Therefore to respond to client feedback, we need to find a way to make that x axis less congested. 

This could be:
* Making x axis text smaller
* Thinning out the ticks on the x axis (although unsure what might be sensible given that the visualisation will grow over time
* Making x-axis angled (which was their request)

Feels like it would be good to be able to go back to them with at least an example of what angled x axis labels might look like - even if we turn out to dislike it. 


(Should be meeting YFF on Tuesday FYI)

**Comment by slowe** [comment]
@ODILMichelle You could also put line breaks in between the months and the years. So:
```
Apr-Jun
1992
```

**Comment by slowe** [comment]
![figure(34)](https://github.com/open-innovations/yff-data/assets/299787/993ae4ca-58d6-481f-9ee2-5431ca54e4a4)
See example above. It would need whoever is generating `src/_data/sources/neet/need_all_data.csv` to make sure that their `quarter_label` label column values get formatted appropriately e.g. `Oct-Dec\n2001`

**Comment by gilesdring** [comment]
Here's the slightly updated 'end of the chart' showing the reliable 'axis end overflow' issue - will always be this now, as labels count backwards...

![Image](https://github.com/open-innovations/yff-data/assets/1731108/5b313ab0-021a-41b2-91d5-d83967905954)

**Comment by gilesdring** [comment]
OK. Thanks for clarifying. I propose then that we create an additional label for the purpose of labelling axes. I'll make a list of the scripts that will need this adding.
