### ISSUE TITLE
Reduce visualisation size so that all data is visible

### ISSUE THREAD

**Issue by taz-chiles** [open-innovations/yff-data#181]
Some visualisations are too large on the page to be able to view all data points and axis labels.

**Comment by gilesdring** [comment]
Need to define:

1. which visualisations are particularly problematic (although we need a solution which works everywhere)
2. what is a normal page
3. do we squash vertically or scale proportionately

**Comment by ODILMichelle** [comment]
@taz-chiles what needs to happen here to ensure we can move this into 'ready'?

**Comment by ODILMichelle** [comment]
@taz-chiles are you happy we can close this?

**Comment by taz-chiles** [comment]
Yes, looks better now - closing as completed
