### ISSUE TITLE
Improve functionality of legend in visualisations

### ISSUE THREAD

**Issue by ODILMichelle** [open-innovations/yff-data#182]
Feedback from YFF: When you click on the line in the legend, it does random things (or nothing) rather than toggling the line on and off

Talk with @ODILMichelle or @taz-chiles to understand problem more as they have replicated this.

**Comment by slowe** [comment]
@taz-chiles and I have had a chat about the UX side of this.

**Comment by ODILMichelle** [comment]
Do you want me to take a look at this? (Wondering as it's 'in review')

**Comment by slowe** [comment]
@ODILMichelle Taz and I have reviewed the new behaviour and are happy with it so you may want to take a look now and see if you are happy with it too.

**Comment by ODILMichelle** [comment]
Hello! Thanks ever so much for this. 

I reckon we can consider this done, but I have opened two new tickets.

#203 - small niggle, hopefully easy to pick up & resolve!
#204 - which is one to discuss whether it is useful or not :)
