### ISSUE TITLE
Sort out 'looking only at quarterly data rather than 3-monthly'

### ISSUE THREAD

**Issue by ODILMichelle** [open-innovations/yff-data#183]
From email at YFF. Need to understand this more

**Comment by ODILMichelle** [comment]
Agreed @gilesdring will email YFF to understand this more.

**Comment by gilesdring** [comment]
Also ask about #176

**Comment by ODILMichelle** [comment]
Email sent, waiting for response

**Comment by gilesdring** [comment]
This will be resolved by selecting a form of words which describes the data as monthly rolling rather than quarter.

Response sent to  YFF

> This data is derived from the monthly rolling figures, but perhaps the wording is a bit unclear, but we can easily fix that. I’ll try and illustrate what will be shown below:
>  
> The most recent published LMS monthly data is from Jan-Mar 2023 (was released on 11 May). Here’s the processing we do, per discussions with Andrea:
 
> Jan-Mar 2023 - keep
> Dec-Feb 2023 - remove
> Nov-Jan 2023 - remove
> Oct-Dec 2022 - keep
> Sep-Nov 2022 – remove
> etc
 
> This means always have the most recent data, and one month in three that will naturally align with the ‘quarterly’ stats.
 
> The next update is tomorrow, so by the end of the day it should be the case that the charts / tables are updated to show Feb-Apr 2023, Nov-Jan 2023, etc.

**Comment by gilesdring** [comment]
Have changed labels on tables and charts from Quarter to 'Rolling 3-month period'. Also added dates to 'about this data' paragraph

**Comment by ODILMichelle** [comment]
I am going to close this issue as I believe it is resolved. No questions were raised about Labour market as presented. 

Let me know if you think otherwise @gilesdring
