### ISSUE TITLE
Add index that captures CPI for 4 main youth related categories

### ISSUE THREAD

**Issue by ODILMichelle** [open-innovations/yff-data#187]

**Comment by luke-strange** [comment]
@ODILMichelle what do you mean by this ticket?

**Comment by ODILMichelle** [comment]
heh, this was something @gilesdring and I were discussing last week. 

So at present in the first visualisation, we're showing 4 CPI categories and 'all CPI", We were wondering if we might be able to show a 'all youth related CPI' value. 

I don't think it's urgent today however - and perhaps one to discuss tomorrow

**Comment by luke-strange** [comment]
Yes we could average across the 4 categories they mention. Would be fairly easy to add.
