### ISSUE TITLE
0 values in Bar charts

### ISSUE THREAD

**Issue by luke-strange** [open-innovations/yff-data#189]
Currently, if a value is 0, it is a blank bar:

![Image](https://github.com/open-innovations/yff-data/assets/92686634/2fade94b-95b2-48a2-96c0-cdbcedbb23a4)

When I first saw this my initial reaction was "why is that data missing?". Wondering if it would be better/possible if we had a thin line in the correct colour that showed it was 0 and you could hover over it like other bars to confirm?

What are your thoughts @slowe

**Comment by slowe** [comment]
@luke-strange Do you have a link to that chart?

**Comment by luke-strange** [comment]
I'm about to push it, so it will be live [here](https://data.youthfuturesfoundation.org/) in a few minutes.

**Comment by luke-strange** [comment]
@slowe pushed now, should be live in the next 5 mins

**Comment by luke-strange** [comment]
@slowe what did you decide to go for in the end?

**Comment by slowe** [comment]
@luke-strange What you said
![Screenshot 2023-06-06 at 13-00-44 Consumer Prices Index - Youth Futures Foundation](https://github.com/open-innovations/yff-data/assets/299787/940b662a-e2ae-461e-9f68-9513b51bfa98)

**Comment by luke-strange** [comment]
perfect. thanks!
