### ISSUE TITLE
Amend text on the CPI page

### ISSUE THREAD

**Issue by ODILMichelle** [open-innovations/yff-data#190]
Probably add a new content heading and explanation about the time series.

**Comment by ODILMichelle** [comment]
@luke-strange just wanted to check, do the CPI categories & the CPI time series visualisations come from the same data set?

**Comment by luke-strange** [comment]
@ODILMichelle yes they do. both from MM23. The start date is 10 years ago from the current month. So next month when the data updates, it will start from June 2023. Is this the desired behaviour?

**Comment by ODILMichelle** [comment]
I believe so, yes! Just wanted to check so I could add appropriate wording to this affect & not misrepresent your work.

Thanks.

**Comment by luke-strange** [comment]
@ODILMichelle  Did you have some wording written for CPI time series or would you like me to add something

**Comment by ODILMichelle** [comment]
I don't have any yet @luke-strange & have run out of time today. Do you think you could take a first stab please?

**Comment by luke-strange** [comment]
@odi-amy  done
