### ISSUE TITLE
Improve tooltip text visibility for narrow/small screens

### ISSUE THREAD

**Issue by ODILMichelle** [open-innovations/yff-data#191]
Images from phone:

**Landing page**

![Image](https://github.com/open-innovations/yff-data/assets/88284441/e400679c-b5d7-4f4c-878d-97743a60d09a)

**Main data page**
![Image](https://github.com/open-innovations/yff-data/assets/88284441/de895df2-b9d4-49ef-ae39-e18f3e94158d)

**Comment by slowe** [comment]
A slightly off-topic observation: the text colour in the orange tooltip has changed from white to black because I've updated the algorithm that calculates the most contrast-y text colour to the same one we are now using in OI Lume Charts. It does a better job.

**Comment by ODILMichelle** [comment]
@slowe - tested it, and it seems to do the trick on the two phones I have access to. Which means I'm happy it's done. 

If you're happy it is done/you've done the testing you want, please feel free to close it!
