### ISSUE TITLE
Review what will be displayed on data dashboard visualisations

### ISSUE THREAD

**Issue by ODILMichelle** [open-innovations/yff-data#192]
Do we want to display:

- Tooltips
- Key
- Multiple lines

Blocked by #150 - we want to see what everything looks like with amended axis

**Comment by ODILMichelle** [comment]
On #150, we're removing the furniture. We may add it back if asked by YFF

**Comment by ODILMichelle** [comment]
Will ask for thoughts about this on 13th Jun

**Comment by taz-chiles** [comment]
Closing this as completed
