### ISSUE TITLE
Review all visualisations on data dashboard landing page

### ISSUE THREAD

**Issue by ODILMichelle** [open-innovations/yff-data#193]
Sense check what is being displayed, ensure we're displaying from CPI & Vacancies (as part of #173) and possibly remove one of the two LTU visualisations.

May need to add one or other visualisations which have been more recently requested e.g. gender, age breakout etc

As part of this will need to ensure that each visualisation added has appropriate anchor links added that takes user to correct visualisation on the page (as outlined on #177)

**Comment by gilesdring** [comment]
I have updated  the headline figures to show this:

![Image](https://github.com/open-innovations/yff-data/assets/1731108/c7d6c867-20ab-4397-a8f3-0e2077876dbc)

The headline board is separate from the visualisations below.

**Comment by gilesdring** [comment]
Have updated with simplified visualisations to look like this:



![Image](https://github.com/open-innovations/yff-data/assets/1731108/c68a638f-4f78-4720-82b0-f4f75c1739b7)
