### ISSUE TITLE
Add vacancy stacked bar chart showing employment by industry

### ISSUE THREAD

**Issue by ODILMichelle** [open-innovations/yff-data#195]
Done: 

- A stacked bar chart which shows industries where young people (broken down by age 16-19 and 19-24) and gender. May not show gender but good to see if it is interesting

**Comment by taz-chiles** [comment]
https://www.nomisweb.co.uk/api/v01/dataset/NM_17_1.data.csv?geography=2092957697&cell=404422913...404422922,404423169...404423178,404423425...404423434,404423681...404423690,404423937...404423946&measures=20100

**Comment by taz-chiles** [comment]
@ODILMichelle probably the same with this one - seems like a nice to have with everything else on. Thinking shall we close as not planned and come back to it if we can ?

**Comment by ODILMichelle** [comment]
I've taken it out of any planned sprints now cos I think you are right. Let's get the must haves cleared (and there are more than enough of them!)

**Comment by taz-chiles** [comment]
Closing #195 as not planned.
