### ISSUE TITLE
Explore idea of showing regional breakdown of employment for young people

### ISSUE THREAD

**Issue by ODILMichelle** [open-innovations/yff-data#196]
A nice to have might be showing geographic breakdown (at something lower than regional). Data to be drawn from Annual Population Survey rather than census. 

(If YFF ask, the census only shows data from 2021 whereas the APS is released quarterly.)

**Comment by ODILMichelle** [comment]
This feels like a nice to have, with a lot of other things on. As such, I suggest we close this?

**Comment by taz-chiles** [comment]
Aye agreed, closing as not planned
