### ISSUE TITLE
Add 'number of vacancies' all time line chart to dashboard

### ISSUE THREAD

**Issue by ODILMichelle** [open-innovations/yff-data#197]
As part of being done, we will need to ensure that the visualisation added has appropriate anchor links added that takes user to correct visualisation on the page (See #177)

**Comment by ODILMichelle** [comment]
Renamed & can now proceed :)

**Comment by taz-chiles** [comment]
Added to the dashboard @ODILMichelle  - I think it looks good! thoughts? 

![image](https://github.com/open-innovations/yff-data/assets/97239140/f8670ce3-5f57-43a1-99bb-cfd449ad8a24)

**Comment by ODILMichelle** [comment]
I think it looks great, thanks! 

I'm mostly distracted and fascinated by the large increase in vacancies early this year :)
