### ISSUE TITLE
Resolve the 404 that shows when you click 'download' on the LTU for young people visualisations

### ISSUE THREAD

**Issue by ODILMichelle** [open-innovations/yff-data#199]
Both rolling 3 years and since 1992 show a 404 when you click 'download' rather than providing the raw data (which is the approach we want to see). 

Adding blocked to this as it doesn't make sense for us to move on this until we've resolved #176 as these visualisations may change.

**Comment by ODILMichelle** [comment]
Unblocked, LTU visualisations are staying the same

**Comment by gilesdring** [comment]
Same issue as #198
