### ISSUE TITLE
Ensure correct visualisation is being shown on vacancy page

### ISSUE THREAD

**Issue by ODILMichelle** [open-innovations/yff-data#200]
Looking at vacancy page it appears we're showing a LTU visualisation rather than anything related to vacancies in first visualisation. 

Can we check this please?

![Image](https://github.com/open-innovations/yff-data/assets/88284441/49d83d9b-8756-47d6-a9f0-1a93b5598da0)

**Comment by taz-chiles** [comment]
@ODILMichelle I have swapped this back now! Closing issue
