### ISSUE TITLE
Ensure that when you click NEET visualisation on data dashboard landing page it takes you to same visualisation on NEET page

### ISSUE THREAD

**Issue by ODILMichelle** [open-innovations/yff-data#201]
Follow guidance Stuart shared on #177

**Comment by taz-chiles** [comment]
Is this a duplicate of #209? If not could you please clarify the difference?

I think this is done - I've added a link and anchor to the correct visualisation on the NEET page

**Comment by ODILMichelle** [comment]
hah, wasn't a duplicate I just didn't put full info in the other one. Will add more tickets about this later (if they are not already picked up!)
