### ISSUE TITLE
Allow users to select and visualise multiple (but not all) lines of a visualisation

### ISSUE THREAD

**Issue by ODILMichelle** [open-innovations/yff-data#204]
This isn't a 'must do', but instead one to have a discussion about. 

Do we want to make it so that those engaging with a page can highlight multiple parts of a visualisation, but not all parts of it? e.g. highlight unemployed rate & economically inactive rate, but not Total NEET rate in the below visualisation? 

![Image](https://github.com/open-innovations/yff-data/assets/88284441/051c0529-3c27-41a1-a94a-0c7ac2f335cc)

**Comment by slowe** [comment]
@ODILMichelle Perhaps I'm missing something but I don't see "unemployed rate & economically inactive rate, but not Total NEET rate" in the screenshot.

The current implentation is my opinion. Things to think about for a more complex user interaction system... If you want to be able to select multiple series, how do you want to do that? Will that method work for mouse, keyboard, and touch inputs (to maintain accessibility)? Will it stop existing behaviours e.g. currently one click/touch/enter can quickly switch between different individual series?

**Comment by ODILMichelle** [comment]
Archiving this as it feels like a 'nice to have' not a 'must do'
