### ISSUE TITLE
Build MVP pipeline for economic indicators report page

### ISSUE THREAD

**Issue by gilesdring** [open-innovations/yff-data#21]

**Comment by gilesdring** [comment]
Pre-requisites

- Need detailed working session on existing report

**Comment by ODILMichelle** [comment]
Economic indicators to focus on initially:
- GDP
- CPI
- Interest rates - need to find out from them where they get this from.

Inquire about what processing they do for vacancies: https://www.ons.gov.uk/employmentandlabourmarket/peopleinwork/employmentandemployeetypes/bulletins/jobsandvacanciesintheuk/january2023

**Comment by ODILMichelle** [comment]
Key notes to be aware of: 

- Looking at interest rates & GPD are new for YFF and/or something Andrea focusses on at present.
- We need to review the formula used by YFF to calculate rolling changes to CPI. Likely to need to discuss this with YDD next week.

**Comment by gilesdring** [comment]
I noticed there was a separate ticket for CPI stats alone - should this one close in favour of #31 and other tickets dealing with GDP / interest rates etc?

**Comment by ODILMichelle** [comment]
I would say yes - so long as we have the right other tickets for each of these? cc @luke-strange @taz-chiles

**Comment by luke-strange** [comment]
I created the CPI stats one - sorry if it's messed with the system.
