### ISSUE TITLE
Add increase/decrease indicator for NEET

### ISSUE THREAD

**Issue by luke-strange** [open-innovations/yff-data#214]
Add an 'increase/decrease' note for the NEET headlines stats. See the CPI headlines and pipeline `scripts/cpi/prepare.py` as an example.

This should be done from the data during the `scripts\neet\prepare.py` stage and written to the `src\_data\sources\neet\headlines.csv` that drives `src\dashboard\neet\_data\visualisation\headline.yml` .

**Comment by taz-chiles** [comment]
Closing #214 as not planned
