### ISSUE TITLE
Amend ordering of dashboard panels so that NEET and labour market pages are at the top

### ISSUE THREAD

**Issue by taz-chiles** [open-innovations/yff-data#223]
Feedback from YFF: 

On the dashboard would make sense to flip it round with NEET and vacancies at the top rather than inflation, given our focus and likely readers.

Amend how the dashboard panels are ordered on https://data.youthfuturesfoundation.org/dashboards/ so that links to the NEET and labour market dashboards appear first.

**Comment by gilesdring** [comment]
Ordering set by explicitly setting the `priority` data key - set in index.njk for labour market and neet pages. Default, set in `src/dashboard/_data.yml` is 0. Higher numbers make pages sort higher. Secondary sort is on title.

This code in `src/pages/dashboards.njk` implements the sort.

```nunjucks
{% for page in search.pages("dashboard", "priority=desc title=asc") | data %}
  {{ comp.superlink({ page: page }) | safe }}
{% endfor %}
```
