### ISSUE TITLE
Amend description of the headline indicator on CPI stats

### ISSUE THREAD

**Issue by taz-chiles** [open-innovations/yff-data#224]
After feedback during the Show & Tell - amend/add some description to explain what the indicator means. 

'Could also put increase/decrease in bold to make it clearer'

**Comment by gilesdring** [comment]
Links to #79

**Comment by luke-strange** [comment]
@ODILMichelle are we still doing this one?

Not 100% sure how we would do this atm, since the "note" is required to be stored in a .csv, which doesn't support text formatting.

**Comment by luke-strange** [comment]
@gilesdring not sure how we might do this, technically speaking.

**Comment by taz-chiles** [comment]
Closing #224 as not planned.
