### ISSUE TITLE
Confirm/add data source for CPI ‘Categories most affecting young people’ visualisation

### ISSUE THREAD

**Issue by taz-chiles** [open-innovations/yff-data#225]
Explain where the data for https://data.youthfuturesfoundation.org/dashboard/cpi/ 'Categories most affecting young people' visualisation is coming from and why these categories have been chosen. 

YFF are doing some analysis on this so may be able to provide a data source that we can link to.

**Comment by gilesdring** [comment]
Linked to #79

**Comment by luke-strange** [comment]
Have sent YFF an email on this, putting in progress.

**Comment by gilesdring** [comment]
@luke-strange  Add direct link to position on pipeline page

```
<span id='dagger'>...</span>
```

Link `page#dagger`
