### ISSUE TITLE
Confirm/add data sources for the vacancies ‘growth in vacancies by sector’ visualisations

### ISSUE THREAD

**Issue by taz-chiles** [open-innovations/yff-data#226]
https://data.youthfuturesfoundation.org/dashboard/vacancies/

Add the correct source of data for the ‘key sectors young people work in’ and ‘sectors where young people want to work’ charts to indicate why these categories have been chosen as most relevant and most desired by young people.

**Comment by gilesdring** [comment]
Linked to #79
