### ISSUE TITLE
Add descriptive text to the ‘vacancies quarterly growth by sector’ visualisations

### ISSUE THREAD

**Issue by taz-chiles** [open-innovations/yff-data#227]
https://data.youthfuturesfoundation.org/dashboard/vacancies/

Add some descriptive text to explain why these sectors are being displayed and where the data is coming from - currently this points to a report published by YFF however they referred to a specific source of data that we could link to. 

Follow up with YFF and add the correct data source to explain why these categories have been chosen and how the figures have been generated.

**Comment by gilesdring** [comment]
Similar to #226
