### ISSUE TITLE
Investigate x axis bug

### ISSUE THREAD

**Issue by taz-chiles** [open-innovations/yff-data#231]
Feedback from YFF: 

Some issues with dates on X axis and fitting in page

**Comment by ODILMichelle** [comment]
@taz-chiles I think @gilesdring has be meaning to pick something about this up. Can you check in with him please?

**Comment by gilesdring** [comment]
Hold off of this until we've had a go at #179

**Comment by gilesdring** [comment]
Duplicates #179
