### ISSUE TITLE
Change CFF map to English Regions (ITL1)

### ISSUE THREAD

**Issue by gilesdring** [open-innovations/yff-data#24]
* Switch to Leaflet map
* Find English Regions shapefile

**Comment by ODILMichelle** [comment]
Guidance was provided by YFF that they are keen to see a visualisation similar to: https://youthfuturesfoundation.org/wp-content/uploads/2022/07/Connect-Futures-launch-image.jpg

I

**Comment by gilesdring** [comment]
The appropriate geography is ITL1

The appropriate geogrhttps://www.ons.gov.uk/methodology/geography/ukgeographies/eurostat

https://geoportal.statistics.gov.uk/search?collection=Dataset&sort=name&tags=all(BDY_ITL1%2CJAN_2021)

https://geoportal.statistics.gov.uk/datasets/ons::international-territorial-level-1-january-2021-uk-bgc-1/about

I think the BGC (Generalised Clipped) is probably appropriate. BFC / BFE is Full resolution, which will be much larger.

NB - the GeoJSON file in that last link is in EPSG:27700 (OS National Grid) co-ordinates, and will need to be re-projected to WGS84, which would make it valid GeoJSON, and easier to use in Leaflet. @slowe Can you help with this? Or do we already have an ITL1 English Region GeoJSON shapefile?

**Comment by slowe** [comment]
@gilesdring Yes I will look into making ITL1 available based on those files (even though I don't think boundaries were changed from NUTS1, just the names/codes). I'll optimise the GeoJSON.

**Comment by taz-chiles** [comment]
I have updated the map to ITL1 level geography however will come back to this, as we did discuss a couple of other changes i.e. replicating the colours in the above visualisation, and converting to leaflet to add pins at specific locations.

**Comment by gilesdring** [comment]
@taz-chiles Given discussions, propose that we don't switch to leaflet map, but ticket that separately - in backlog, as it sounds like we might also need to revisit the component to allow more config options (additional layers, etc).

@slowe Do we have English Regions ITL1 SVG maps? Or could we render the GeoJSON above to SVG for inclusion?

**Comment by slowe** [comment]
Between @taz-chiles and me we have got markers working on both `svg-map` and `leaflet-map`. They can be positioned (`latitude` and `longitude`). A `tooltip` can be set. An `icon` can be chosen from a predetermined list (default, geo, geo-alt, asterisk, pin, balloon, balloon-heart, chat-square) or defined manually. The `color` can be set. Here are four examples:
![Screenshot 2023-03-30 at 15-21-10 Connected Futures - Youth Futures Foundation](https://user-images.githubusercontent.com/299787/228884786-847bb35d-a281-4c0c-8d63-55886fcd4a3f.png)

**Comment by taz-chiles** [comment]
We've added markers for each of the awarded partnerships so happy to say we've replicated the YFF graphic minus the exact colours (and the man standing on East Anglia!). I don't think we need to convert to leaflet given it does what we need now, but we can open another ticket if something else comes up.

I'll stick this one in review for @gilesdring and @ODILMichelle to take a look at before closing.

**Comment by gilesdring** [comment]
Reviewed https://data.youthfuturesfoundation.org/projects/cff/ (please add links to ticket!)

Looks good with following observations :

- Map does not scale down on small screens - wider than iPhone for example. This throws the page out
- numbers shown in tooltip don’t match: e.g. North West has awarded to Burnley and Blackpool - tooltip says 1 awarded
- Contrast between yellow and white means I can’t see outline of regions.

**Comment by ODILMichelle** [comment]
A few other observations from me:

- I'm not a massive fan of using purple and yellow. It feels a bit 'UKIP-y' to me, which is likely not to be a look YFF want to associate themselves with. 
- Is there a reason we've chosen to label Plymouth, Bristol, Liverpool (in caps) and Newcastle? Feels like either naming the locations of partnerships (as in the image supplied by YFF) or not naming anything until you hover over the appropriate tool tip might be a better approach.

**Comment by taz-chiles** [comment]
@ODILMichelle @gilesdring [Updated the page with these changes](https://data.youthfuturesfoundation.org/projects/cff/)

- Not able to replicate the scaling issue on mobile, it looks fine on my device and when I scale down on my computer but I'll have a look on some other browsers
- I've updated the data to include the correct number of awarded regions, which also fixes the colouring issues. Let me know if other colours would be preferable. 
- I've removed the place labels

Let me know your comments, thanks
