### ISSUE TITLE
Add headline figures that show baseline unemployment & economically inactive figures

### ISSUE THREAD

**Issue by ODILMichelle** [open-innovations/yff-data#241]
This will be on the labour market page: https://data.youthfuturesfoundation.org/dashboard/labour-market/

It will allow users the chance to compare the experience of young people more effectively

To be clear: unemployment figures for general working age population. Will require additional data extract

**Comment by gilesdring** [comment]
I don't think there is a single field we can pull for this - would need to construct a 16-64 figure. Unless the ILO stats can be used. 

Could do with some advice from @ChristianSpence on this.

**Comment by gilesdring** [comment]
Looks like these are the ones:

LF2Q,LFS: ILO Unemployment rate: UK: All: Aged 16-64: %: SA,%,NA
LF2S,LFS: Economic inactivity rate: UK: All: Aged 16-64: %: SA,%,NA

**Comment by gilesdring** [comment]
![Image](https://github.com/open-innovations/yff-data/assets/1731108/148ba6d6-92fc-45f1-b7bb-07e250d45975)




![Image](https://github.com/open-innovations/yff-data/assets/1731108/d6bfba3b-e10f-42a4-9607-500e15b3c590)
