### ISSUE TITLE
Ensure that when you click the NEET headline figure on dashboard landing page, you are taken to appropriate part of the page

### ISSUE THREAD

**Issue by ODILMichelle** [open-innovations/yff-data#244]
Headline figure is the top most number about NEET on data dashboard landing page: https://data.youthfuturesfoundation.org/

Should resolve to picture below (ensuring the same padding as seen on other pages)

![Image](https://github.com/open-innovations/yff-data/assets/88284441/34eb57f6-8151-4c0a-8614-ac293c76af5b)

**Comment by ODILMichelle** [comment]
Related tickets (i.e. similar actions but different pages)
- #246  
- #245

**Comment by gilesdring** [comment]
I disagree that the headline NEET figure should link to a the chart - I'm instead proposing linking any headline just to the dashboard (no anchor). Any charts should link to the relevant chart.

It might be good if the dashboard on the NEET page itself links further down.
