### ISSUE TITLE
Investigate missing data for long-term unemployment over 12 months

### ISSUE THREAD

**Issue by gilesdring** [open-innovations/yff-data#249]
![Image](https://github.com/open-innovations/yff-data/assets/1731108/372371b1-cc5b-421e-99ba-1650917460a9)

Most recent data for LTU is missing. Is this a one off, or due to a change in publication. Should we contact ONS to check if this in on purpose.

**Comment by gilesdring** [comment]
Replaces #148 as the specific example of this

**Comment by gilesdring** [comment]
See also #222

**Comment by gilesdring** [comment]
Options emerged - setting to zero if NA, or removing completely

**Comment by gilesdring** [comment]
![Image](https://github.com/open-innovations/yff-data/assets/1731108/b8c85469-4901-49bf-80c9-4df14128a612)

The issue is missing 16-17 Y/O data, so if this has happened (as it does) we fall back to using 18-24 figures. Looks fairly secure.

**Comment by gilesdring** [comment]
@taz-chiles @ODILMichelle Could you take a look? Ta

**Comment by taz-chiles** [comment]
@gilesdring Looks good to me, no missing data and downloads fine - happy to close?
