### ISSUE TITLE
Amend titles of visualisations on LMS comparison charts

### ISSUE THREAD

**Issue by gilesdring** [open-innovations/yff-data#253]
for Age related - should say All ages (18-24)
for gender - should say all people

![Image](https://github.com/open-innovations/yff-data/assets/1731108/46c9de4e-a81b-4300-9601-64cbf32786c4)

**Comment by luke-strange** [comment]
Not too sure what you mean by this @gilesdring

**Comment by gilesdring** [comment]
The "third tab" in the comparison tablets should be named in a manner consistent with the other two. So for the age-related comparisons it should be:

16-17 / 18-24 / 16-24

And for gender it should be

Women / men / all people

Sows that make sense?

**Comment by luke-strange** [comment]
Ah, there's a slight problem for the gender one. Because the chart is used in 3 places, changing the name affects them all.

**Comment by gilesdring** [comment]
Have a solution to this.

**Comment by gilesdring** [comment]
![Image](https://github.com/open-innovations/yff-data/assets/1731108/2021793d-8247-461a-b4dc-9ac3b1ba74ad)



![Image](https://github.com/open-innovations/yff-data/assets/1731108/e6f5576a-16e2-4099-9d9c-9ebe15c354c4)
