### ISSUE TITLE
Tidy up Youth Focussed CPI visualisation

### ISSUE THREAD

**Issue by gilesdring** [open-innovations/yff-data#257]
- [x] Move move youth focused to the top, add a note to describe how we aggregated it.

- [x] Separate out "all" and "youth" from others.

- [x] Add to time series.

- [ ] Validate calculation with YFF

**Comment by luke-strange** [comment]
wording will need some refining but have completed bullet points 1&2.

**Comment by luke-strange** [comment]
Currently, we are just doing a mean average across the 4 categories. Will need YFF input to hear if a weighted average is better and what those weightings and the reasoning behind them are.

**Comment by luke-strange** [comment]
Going to close this ticket and open a new one for weighted-averages of youth-focused index.
