### ISSUE TITLE
Build processing pipeline for unemployment by constituency

### ISSUE THREAD

**Issue by taz-chiles** [open-innovations/yff-data#268]

**Comment by gilesdring** [comment]
File from upstream registered with DVC - stored in `working/upstream/labour-market_latest_by_pcon_2010.csv`. You'll need to ensure that `dvc update -R working/upstream` runs before checking out.

It should be as simple as loading the csv and then using a simple filter...

```python
youth_unemployment = data.loc[data.variable_name == 'Unemployment rate - aged 16-24', ['geography_code', 'value', 'notes']]
```

Pivot won't work, cause we probably also want the notes field.

**Comment by taz-chiles** [comment]
Thanks @gilesdring - closing #268 as complete
