### ISSUE TITLE
Add key visualisations onto dashboard listing page

### ISSUE THREAD

**Issue by taz-chiles** [open-innovations/yff-data#274]

**Comment by gilesdring** [comment]
Have created a Lume processor which searches for the following style of markup:

```html
      <div data-injector-url="<page url>" data-injector-selector="<css selector>"></div>
```

This runs after the file is rendered, and searches the page with the url specified. It then scans the DOM for the first element that matches the supplied selector, and injects the content inside the element tagged with the data-injector-url and data-injector-selector.
