### ISSUE TITLE
Add number of applications to CFF headline stats

### ISSUE THREAD

**Issue by gilesdring** [open-innovations/yff-data#28]

**Comment by taz-chiles** [comment]
Added the number of applications made. 
Calculated from the count of rows in the "application areas" tab of the [CFF dataset](https://odileeds.sharepoint.com/:x:/r/sites/OpenInnovationsPrivate/_layouts/15/Doc.aspx?sourcedoc=%7BFD898FF9-60B6-407E-AEED-F55254835259%7D&file=Data%20on%20local%20authorities%20and%20regions.xlsx&action=default&mobileredirect=true) shared with us by YFF.
