### ISSUE TITLE
Show 16-64 age groups on Employment maps, instead of 16+

### ISSUE THREAD

**Issue by taz-chiles** [open-innovations/yff-data#283]

**Comment by gilesdring** [comment]
Have done the APS data, but claimant data is a bit more fiddly.


![Image](https://github.com/open-innovations/yff-data/assets/1731108/f243ca75-8eff-450b-a31c-d8574db3c0a4)

**Comment by taz-chiles** [comment]
@gilesdring cool, I'll present back as is for now - can we select 'Aged 16-24', 'Aged 25-49', and 'Aged 50+' excluding 65+ and present the total?

**Comment by taz-chiles** [comment]
Closing this as completed for now. The census data we have added is for 16-24 age groups, if YFF want other age groups to be shown then we can pick this up separately
