### ISSUE TITLE
Change message in site banner

### ISSUE THREAD

**Issue by gilesdring** [open-innovations/yff-data#291]
Also, can we remove this:
 
![Image](https://github.com/open-innovations/yff-data/assets/1731108/c03d74ea-dd4d-425d-b122-ec122365c83b)
 
And replace it with just Please send us feedback here?

**Comment by gilesdring** [comment]
Have replaced header / footer feedback with:



![Image](https://github.com/open-innovations/yff-data/assets/1731108/6e591edb-bee8-46f6-b29f-92748e89bfbf)


Set in <src/_includes/partials/feedback.njk>

**Comment by taz-chiles** [comment]
Closing #291 as completed thanks Giles
