### ISSUE TITLE
Amend autoLegend to allow negative scale

### ISSUE THREAD

**Issue by taz-chiles** [open-innovations/yff-data#297]
The legend on maps/overlaps/ (below) caps at 0, however the data covers a range of positive and negative values that are not percentages. The auto-generated legend needs amending to reflect this

![Image](https://github.com/open-innovations/yff-data/assets/97239140/3c72f331-1840-4066-866e-e05abf394413)

**Comment by gilesdring** [comment]
Changes added:

* Default formatter is now just a straight representation of the value.
* Default rounding is nearest number (up / down, based on max or min)
* Can override formatter and round as follows:

```js
autoLegend({
  formatter: percentFormatter,
  roundTo: 5
})
```

The formatter can be any function - either a js, or if in Nunjucks, a macro.

**Comment by taz-chiles** [comment]
This is done, thanks Giles - closing as completed
