### ISSUE TITLE
Create International Comparisons page with initial visualisations

### ISSUE THREAD

**Issue by taz-chiles** [open-innovations/yff-data#311]
We have committed to building another page presenting international comparisons of OECD data, presumably in the Maps section but this hasn't been specified by YFF. We will need a scoping session with Andrea to define the specific data sources.

After an initial exploration of OECD data, it looks like these datasets could be interesting to visualise: 

- **Educational attainment and labour-force status:** Employment, unemployment and inactivity rate of 25-64 year-olds, by educational attainment.
- **LFS by sex and age**

* Do we want to include an international map?

**Comment by gilesdring** [comment]
These links send you to a report page with a manual download, it may be easier to download using the API 

Converting current OECD unemployment and employment data to rates (to present on the international map)
https://data.oecd.org/emp/employment-rate-by-age-group.htm

NEET rate by country, age 15-19 then 20-24 
OECD NEET data: 
https://data.oecd.org/youthinac/youth-not-in-employment-education-or-training-neet.htm

Most recent low wage rate (%) per country, to be added to international map
Low vs high wages by OECD country:
https://data.oecd.org/earnwage/wage-levels.htm

**Comment by gilesdring** [comment]
Added automatic download of the lfs_by_sex_and_age file, also into `data/raw/oecd`. Have updated the pipeline in yff-data to deal with this as well.

**Comment by taz-chiles** [comment]
MVP International Dashboard is completed, amendments to be ticketed up separately.
