### ISSUE TITLE
Fix styling issue on CFF headlines

### ISSUE THREAD

**Issue by taz-chiles** [open-innovations/yff-data#313]
Something funky going on

![Image](https://github.com/open-innovations/yff-data/assets/97239140/3d1ff54c-3442-42d6-81b2-139e0951b20b)

**Comment by harith-hacky03** [comment]
Can you please assign it to me?

**Comment by slowe** [comment]
@taz-chiles I've fixed it in 1f61bec0cd47371384bc6320a62e39cb944754c9 by swapping over to OI Lume Viz dashboard
