### ISSUE TITLE
Visualise DfE data on GCSE Achievement A - C

### ISSUE THREAD

**Issue by taz-chiles** [open-innovations/yff-data#315]
Education Dashboard

Following discussion with YFF on 9th January - additional datasets will be added to the Education dashboard. 

Download link: [https://explore-education-statistics.service.gov.uk/find-statistics/key-stage-4-performance](https://explore-education-statistics.service.gov.uk/find-statistics/key-stage-4-performance) 

This downloads a zip file with a number of datasets. We are aiming to visualise the datasets listed below. To start with, they can be added as additional layers to the hexmap at **local authority** level.

Dataset: '2223_la_data_provisional' - I think standard achievement rates come from this dataset.
Variables I think we are interested in:
- Local authority geography
- 'version' - Final
- 'avg_att8' - 'Average Attainment 8 score of all pupils'
- 'avg_p8score' - 'Average Progress 8 score of all pupils'

Dataset: '2223_la_char_data_provisional'
Variables:
- Local authority geography
- 'version' - Final
- 'avg_att8' & 'avg_p8score' broken down by: 
     - 'gender' 
     - 'ethnicity_major'
     - 'free_school_meals'
     - 'sen_status'

**Comment by taz-chiles** [comment]
@gilesdring, could we chat about this? - do you think you could build a pipeline to get this ready for visualisation? I believe it is released once for each academic year.

It will need to replace everything that's on there currently as we're not interested in constituency geographies any longer.

**Comment by slowe** [comment]
Example of the structure for a file that will drive the visualisations.

![Image](https://github.com/open-innovations/yff-data/assets/299787/7564bf66-836b-46c1-85e7-d139d5b372e6)

**Comment by taz-chiles** [comment]
Closing #315 as completed
