### ISSUE TITLE
Remove key & amend colouring of CFF map

### ISSUE THREAD

**Issue by ODILMichelle** [open-innovations/yff-data#36]
I don't think we need to show whether a region has 1 or 2 CFF awards using a colour scale - and a key showing two colours for those regions in which awards have been made is a little confusing. 

Can we remove the key, and explore different colouring options for the visualisation. This could be e.g. no colours, just two colours, different colours for all the regions (a little similar to YFF's map, although this seems to give colours for all of the midlands, and the north, all the same: https://youthfuturesfoundation.org/wp-content/uploads/2022/07/Connect-Futures-launch-image.jpg)

What does done look like:

- [ ] Clearly able to see the borders between all regions - this could be through use of a black border, or through no two light coloured regions neighbouring each other.
- [ ] No key
- [ ] Colour scheme leans into the branding on the site, and doesn't lean towards making anyone thinking too much of politics. This means, no purple and yellow together, no blue & red (too Tory vs Labour), and not having patches of black & yellow (might be considered SNP-esque).

**Comment by gilesdring** [comment]
@taz-chiles @ODILMichelle What do you reckon to:



![Image](https://user-images.githubusercontent.com/1731108/233436722-02377933-850e-434f-a06e-5ca6653877d9.png)


https://github.com/open-innovations/yff-data/blob/622f567ef64c65f454006ba587bfe1494395f4ee/src/projects/cff/_data/visualisations.yml#L20-L22

**Comment by gilesdring** [comment]
Fixed another issue that this created with transparent hovers this morning. Should be good to go now!

**Comment by taz-chiles** [comment]
Very nice @gilesdring! I like the consistent colour scheme, more professional. Did you amend this in the component itself or just this visualisation?

**Comment by gilesdring** [comment]
Mostly the viz. I selected a different colour scheme from the set in one of the library files. I added a new one with no transparency to avoid the problem with the hover pop up being transparent, which looked rubbish!

**Comment by gilesdring** [comment]
This would appear to be done
