### ISSUE TITLE
Make it easy to hover over each icon on the CFF map

### ISSUE THREAD

**Issue by ODILMichelle** [open-innovations/yff-data#38]
It's very hard to get the Nottingham marker to select at present as 'East Midlands' keeps popping up when the cursor is in that vicinity.

Also noticed that when approaching the center of the marker, the hover function reverts to sharing information about the region (i.e. it seems to be acting as if it were hollow)

This may be one ticket, or two. I wasn't quite sure on the best approach.

**Comment by gilesdring** [comment]
I think the hole in the marker is causing the problem here...

**Comment by gilesdring** [comment]
Have updated so the marker hole is filled with a transparent circle. Should mean that you can hover more easily.

@ODILMichelle Take a look at https://data.youthfuturesfoundation.org/projects/cff/ if you'd be so kind!

I think the Notts marker issue is a it more involved, as it's down to the location of the hover. I'll raise a separate ticket for that!

**Comment by gilesdring** [comment]
New ticket raised to describe the Derby & Nottingham issue #56

**Comment by ODILMichelle** [comment]
Thanks. Looks grand..
