### ISSUE TITLE
Create visualisation on QLFS dashboard of economic inactivity split by gender

### ISSUE THREAD

**Issue by gilesdring** [open-innovations/yff-data#41]
Page 4 of https://odileeds.sharepoint.com/sites/OpenInnovationsPrivate/Shared%20Documents/Projects/2023/YFF%20-%20Phase%202/Examples%20of%20analysis/April%20Labour%20Market%20Release.pptx?web=1

![Image](https://user-images.githubusercontent.com/1731108/233059924-1a1886e1-4d5f-497a-a9c5-51c8e206cdda.png)

**Comment by taz-chiles** [comment]
To confirm with YFF that they still want to see economic inactivity split by gender

**Comment by ODILMichelle** [comment]
Nothing came up about this in our last call. @luke-strange @taz-chiles @gilesdring suggest we archive this - unless we want to dive in and do it?

**Comment by ODILMichelle** [comment]
Now a duplicate.
