### ISSUE TITLE
Create graphs for NEET economic inactivity by gender

### ISSUE THREAD

**Issue by gilesdring** [open-innovations/yff-data#44]
![Image](https://user-images.githubusercontent.com/1731108/233061583-70d27a84-a9ed-4e17-bbe7-520d359dd78a.png)

**Comment by gilesdring** [comment]
Blocked by #51

**Comment by taz-chiles** [comment]
This ticket is no longer blocked by #51

**Comment by luke-strange** [comment]
Recreated at http://localhost:3000/dashboard/neet/
