### ISSUE TITLE
Draft and add copy for QLFS report

### ISSUE THREAD

**Issue by gilesdring** [open-innovations/yff-data#46]
This is not to cover the full text from YFF, but a check for the MVP dashboard to ensure readability prior to show and tell.

**Comment by gilesdring** [comment]
Need to complete #39 #40 #42 (and maybe #41)

**Comment by gilesdring** [comment]
To include

1. Introduction to dashboard - covering that this is an MVP
2. Brief descriptions of the derivation of each graph

**Comment by gilesdring** [comment]
- [ ] Update to separate Not in FTE (derived from A06) from Long-Term Unemployment (derived from UNEM01), add level 2 headings and a brief description
- [ ] Add more description re: AO6 and UM data sets on QLFS page.

**Comment by ODILMichelle** [comment]
Apologies for late thought on this - but one additional thing:

- [ ] Ensure we add 'rate' consistently e.g. add it to tab heading for 'Long-term unemployment', and review whether it should also be used in the headline figures.

**Comment by ODILMichelle** [comment]
Hey. @luke-strange - just to ask. Should. we have percents in the headline boxes? e.g. isn't the headline figure 'overall unemployment: 10.5%'?

**Comment by luke-strange** [comment]
@ODILMichelle I think Taz is doing this now.
