### ISSUE TITLE
Create CPI bar chart using derived percentage change

### ISSUE THREAD

**Issue by taz-chiles** [open-innovations/yff-data#53]
Create a bar chart replicating the image below using our inferred formula

[ ] Using Table 21 index values, infer percentage change over 1 month, 12 months and quarter

![Image](https://user-images.githubusercontent.com/97239140/233123494-0fc67a42-d9f3-466c-b687-3c6f170df81e.png)

**Comment by luke-strange** [comment]
@ODILMichelle yes.

**Comment by luke-strange** [comment]
![Image](https://user-images.githubusercontent.com/92686634/233680873-48484add-6215-42d3-9ff2-f20067fa88b7.png)
