### ISSUE TITLE
Create CPI bar chart using formula provided by YFF

### ISSUE THREAD

**Issue by taz-chiles** [open-innovations/yff-data#54]
Replicate the bar chart provided by YFF below, showing CPI percentage change on monthly, 12 month and quarterly basis

![Image](https://user-images.githubusercontent.com/97239140/233124375-a6b16c1f-4b09-4f66-b63c-333362571f18.png)

**Comment by gilesdring** [comment]
Is this officially closed? If so, please close ticket! Ta!
