### ISSUE TITLE
Automating chart ranges/labels

### ISSUE THREAD

**Issue by luke-strange** [open-innovations/yff-data#57]
When I was creating the CPI bar chart, I realised that this data will update monthly, and therefore it's feasible that the ranges of percent change might change significantly (e.g. max value becomes much larger and then goes off the chart, because `max` and `min` are set manually). 

Currently, I have written the max and min values form the data to a stats.json file, and so it's working out how to implement these in the `visualisations.yaml` file that I need help with.

Currently, I have written the following code 

![Image](https://user-images.githubusercontent.com/92686634/233681989-2db94b3f-648e-4b53-bba4-865dba843366.png)

which is located in `scripts\cpi\transform_v2.py`

I think this would likely be better located in `prepare.py` as its more of a pipeline process step.

**Comment by luke-strange** [comment]
We need to write a script that automatically produces the following:
[] min and max values for each axis( if applicable)
[] ticks for each axis including a value and label.
[] the date/month of the most recent data that has been used.

and writes them to a file that can be used by the visualisations.yaml script

**Comment by gilesdring** [comment]
I think the simplest / quickest way to achieve this is to modify the visualisations.yaml file, based on the following code:

```python
import yaml

# Read config from file
with open(path_to_file) as f:
  viz = yaml.safe_load(f.read())

# Update the viz definition
print(viz[1]['config']['axis']['x']['max']) # prints current value
viz[1]['config']['axis']['x']['max'] = 40
print(viz[1]['config']['axis']['x']['max']) # prints 40

# Write config to file
with open(path_to_file, 'w') as f:
  f.write(yaml.dump(
    viz,
    default_flow_style=False
  ))
```

**Comment by luke-strange** [comment]
For line charts showing percentages, YFF want them to start at 0, so I think this will be a case of rounding to nearest 5 of max value, then dividing by 4 to create the tick values.

**Comment by gilesdring** [comment]
I'd say rounding up to nearest five. Ticks would be on 5 or 10?

**Comment by luke-strange** [comment]
Closing this ticket as the generation of values and labels is done, and making a new one for writing the results to the yaml file.

You can find the function called `tick_gen` located in `scripts/util/util.py`
