### ISSUE TITLE
Draft and add copy for CPI report

### ISSUE THREAD

**Issue by gilesdring** [open-innovations/yff-data#60]
This is not to cover the full text from YFF, but a check for the MVP dashboard to ensure readability prior to show and tell.

To include

1. Introduction to dashboard - covering that this is an MVP
2. Brief descriptions of the derivation of each graph

**Comment by gilesdring** [comment]
- [ ] Add Economic indicators topic tag
- [ ] Separate the visualisations

**Comment by luke-strange** [comment]
Close as complete
