### ISSUE TITLE
Check all pages for consistency

### ISSUE THREAD

**Issue by gilesdring** [open-innovations/yff-data#62]
Check 

- [x] Chart axis labelled
- [x] Titles
- [x] Legend if required
- [x] Tooltips for sensible rounding, etc
- [x] Data tables on all dashboard pages

**Comment by ODILMichelle** [comment]
From previous convo with YFF, we're to round to 1 decimal place. 

Longterm-unemployment tooltip currently a little bit longer than that ;)

**Comment by luke-strange** [comment]
from a consistency point of view i think this is pretty much done - the pages look and feel the same and have same content.

**Comment by ODILMichelle** [comment]
Happy with this for now. Let's say it is done & we can re-review in the future if needed!
