### ISSUE TITLE
Add 'blocky' list for topic tags

### ISSUE THREAD

**Issue by ODILMichelle** [open-innovations/yff-data#65]

**Comment by gilesdring** [comment]
This looks like this now

https://data.youthfuturesfoundation.org/topics/

![image](https://user-images.githubusercontent.com/1731108/234689669-79f927bf-66c1-459e-b2dd-c6c6f23a8aeb.png)

**Comment by ODILMichelle** [comment]
Love the speed - thanks!

I will likely have one or two comments on the style in future in terms of how it looks on a desktop, but lets get agreement from L23 about the idea & implementations before we get too down in the weeds!
