### ISSUE TITLE
Add intro text for individual topic pages

### ISSUE THREAD

**Issue by ODILMichelle** [open-innovations/yff-data#66]

**Comment by ODILMichelle** [comment]
@gilesdring is this done, or did I just somehow apply the wrong label?

**Comment by gilesdring** [comment]
It's done if you like the following page...

https://data.youthfuturesfoundation.org/topic/apprenticeships/

**Comment by ODILMichelle** [comment]
Heh, I was presuming my own incompetence, not accounting for your speedy work!

Page looks good - although the font for the intro text might benefit from being made more obvious. Given the colour, size and style of the rest of the page, this feels a little odd/unnoticable. But that might not be a bad thing.

**Comment by gilesdring** [comment]
I've tweaked a bit to make the tag more prominent. Closing for now. We can revisit later if needed.
