### ISSUE TITLE
Create a time series showing number of estimated vacancies in thousands

### ISSUE THREAD

**Issue by taz-chiles** [open-innovations/yff-data#67]
From here: https://www.ons.gov.uk/employmentandlabourmarket/peopleinwork/employmentandemployeetypes/bulletins/jobsandvacanciesintheuk/april2023

This is dependent on ticket #35 

[ ] Create a vacancies index.njk page under src - dashboard - vacancies 
[ ] Add line chart with number of vacancies in thousands per quarter
[ ] Add brief textual description of chart

**Comment by ODILMichelle** [comment]
Hey @taz-chiles - just wanted to check on this. My notes for the vacancies visualisations say that we agreed to develop two visualisations related to vacancies:

- Estimated number of vacancies, quarterly. 
- Growth by sector 

I just wanted to check both were covered by the above ticket - or given YFF noted the growth by sector is a secondary measure at present, whether we decided to deprioritise this at present until we've developed the pipeline & first visualisation set (or if we need additional clarity about the growth by sector stuff - which I'm happy to go and try to solve!)

**Comment by taz-chiles** [comment]
Hi @ODILMichelle - thanks, yes I meant to add a second ticket for this visualisation - here's the ticket - #70 

My thinking was that the growth by sector was a secondary measure and less of a priority, however it looks like they won't be too much trouble to visualise at the same time so I will take a look at them both!

**Comment by taz-chiles** [comment]
@ODILMichelle @gilesdring @luke-strange first pass at vacancies data here: 

https://data.youthfuturesfoundation.org/dashboard/vacancies/

Let me know your thoughts!
