### ISSUE TITLE
Add brief summary to the CFF project page

### ISSUE THREAD

**Issue by taz-chiles** [open-innovations/yff-data#68]
Currently this says "PROJECT DETAILS GO HERE" - replace this with something meaningful to describe the page.

**Comment by ODILMichelle** [comment]
And is 'Local Partner' the correct name for the first column of the table on this page? It feels like what is in that column is 'location' or something similar? Feel free to correct me if I am incorrect!

**Comment by taz-chiles** [comment]
@ODILMichelle I have moved the map a little further up however think it makes sense to have the headlines at the top? 

I've used Local Partner as it matches up with their own CFF page, but we could perhaps use 'Area' instead or something like that - I think it's fine as is but let me know if you'd rather change it. 

The links in the table are the same as on the YFF's CFF page aye, I've just condensed the descriptions for each area into the table. 
 
I've also added a very brief description at the top of the page, may tweak before Tuesday.
