### ISSUE TITLE
Test a colour change on CPI dashboard

### ISSUE THREAD

**Issue by ODILMichelle** [open-innovations/yff-data#69]
Re-reviewing the CPI dashboard this morning (https://data.youthfuturesfoundation.org/dashboard/cpi/) I noticed that on one page we're using red (monthly), orange (quarterly) and a yellow-ish (yearly) colour to show the headline figures, and then using different colours for these same items in the barchart below (e.g. blue for quarterly change & orange for yearly change). 

This creates a little bit of cognitive dissonance - although the colours do look great (especially in the bar chart!).

Before Tuesday @luke-strange & @taz-chiles could you test whether using the same colours to refer to the same time period in both the headline stats & visualisation a) is possible b) results in a slightly better feel to the page?

**Comment by ODILMichelle** [comment]
(Don't spend too long on this - if it's not a quick thing to explore, we can always just mention it as something we need to work through. when we meet YFF on Tuesday)

**Comment by luke-strange** [comment]
Fixed.
