### ISSUE TITLE
Identify key visualisations and headline stats to be added to the homepage

### ISSUE THREAD

**Issue by taz-chiles** [open-innovations/yff-data#71]
To follow up with YFF via email initially - this can just be a list of figures and visualisations from each of the dashboard pages.

**Comment by taz-chiles** [comment]
I've started jotting down a list of the key visualisations and headline stats that may be added to the homepage. 

https://docs.google.com/document/d/1BWNl6lqUxSthBH3GM3V_nZF6sp8sySHWvlczlNre4DI/edit?usp=sharing

**Comment by ODILMichelle** [comment]
Made some comments. 

@gilesdring just flagging to you that there may be a desire to add an arrow indicator to a headline box on the dashboard to show whether a number has increased or decreased. Does that seem like something problematic to do? (Not adding it as a separate ticket yet as we've not confirmed this)
