### ISSUE TITLE
Update Toolkit page to tie in with launch in May

### ISSUE THREAD

**Issue by taz-chiles** [open-innovations/yff-data#72]
Some changes need to be made to the Toolkit project page - to follow up with Anna about this initially to check there is nothing that needs to be done now.

Toolkit is expected to be released at the end of May.

**Comment by ODILMichelle** [comment]
Followed up with Anna now, will let everyone know if any changes are needed now - or if this is something we schedule for sprint 6 or 7.

**Comment by ODILMichelle** [comment]
No changes to be made for now. YFF have said to follow-up towards end of May as originally planned. Have therefore updated sprint timing to reflect this.

**Comment by ODILMichelle** [comment]
Emailed them to ask for link to toolkit, and visuals. @taz-chiles, I'll leave this to you to implement, if thats ok?

**Comment by ODILMichelle** [comment]
Chased again

**Comment by gilesdring** [comment]
Updated
