### ISSUE TITLE
Agree on narrative & narrative context across the microsite

### ISSUE THREAD

**Issue by taz-chiles** [open-innovations/yff-data#79]
Agreed with YFF that we would send over a template doc so that they can make amendments and additions to the content and provide background context for each page.

- [x] Create a template doc for each page with existing text and space to provide comments on styling and design. 
- [x] Share the template with YFF for feedback
- [ ] Apply content and style changes to the microsite

Pre-reqs - develop/update templates for:

- [x] Labour market: https://docs.google.com/document/d/1m7wTV6_9bQ7KP0NVrFWsKAnPTZCPPkLHiPrXlmDf70U/edit
- [x] CPI: https://docs.google.com/document/d/1MEnhV-C2GPWoNvAtn8yxRTjYGa4Eq-VSiHTrzhpypVI/edit
- [x] Vacancies: https://docs.google.com/document/d/1WX08XfQ-DvrEfojgZneOVr7A3i1dQ2ZDOi2PMCfpkgM/edit
- [x] NEET: https://docs.google.com/document/d/1tGc7TXId-dyEuMqN4MbQkEjgtQFlBj_CaWg4atg1IMw/edit
- [x] CFF: https://docs.google.com/document/d/1ansqVGjFbXAmfsiRoozWwbc3HGPsOW_oIgnQXxfxrQA/edit

**Comment by ODILMichelle** [comment]
See also #92 for some specific points related to CPI. 

Suggest we do not engage YFF on narrative at this point in time, until we have clarity on approach we are taking.

**Comment by taz-chiles** [comment]
[QLFS Content template](https://docs.google.com/document/d/1m7wTV6_9bQ7KP0NVrFWsKAnPTZCPPkLHiPrXlmDf70U/edit?usp=sharing)
[NEET Content template](https://docs.google.com/document/d/16awGiTlCYcpXz6scabDS32VU6iGW1x-pMwdUcUYWVww/edit?usp=sharing)

We can hold off on CPI and vacancy content for now, but these should be ready to share with YFF for their input.

**Comment by ODILMichelle** [comment]
As part of this, will need to ensure narrative text for CPI page explains youth context (was its own seperate ticket, removed now)
