### ISSUE TITLE
Add descriptive text to specify source of headline stats

### ISSUE THREAD

**Issue by taz-chiles** [open-innovations/yff-data#80]
It needs to be clear what the headline stats are presenting and how they are derived - add a description to all pages that have headline stats to specify their source and context.

**Comment by taz-chiles** [comment]
@ODILMichelle I have added footnotes to the headline stats to give a little more context, comments welcome! 

http://localhost:3000/dashboard/qlfs/
http://localhost:3000/dashboard/cpi/
http://localhost:3000/dashboard/neet/

**Comment by ODILMichelle** [comment]
Hey @taz-chiles - afraid I won' be able to see anything pointing to locally hosted versions of your work to date. 

I've seen some really interesting sub-headings/footnotes added to the headline stats on the live site however (see attached). Is this what you are referring to? 
![Screenshot 2023-05-05 at 08 07 34](https://user-images.githubusercontent.com/88284441/236396504-e0f90e35-8a8c-4452-8fae-2fda14ed974d.png)

**Comment by taz-chiles** [comment]
@ODILMichelle doh! Updated the links in the comment. Yes, this is what I was referring to. We could either include the text description in the dashboard panel itself (my preference) or outside of the panels as a text description beneath (might be cleaner).

**Comment by ODILMichelle** [comment]
I this is great - shall we say it is done, barring any further feedback from them?

**Comment by taz-chiles** [comment]
@ODILMichelle Sounds sensible aye, we can raise it in our next feedback session.
