### ISSUE TITLE
Extend overall NEET rate chart to pre-pandemic

### ISSUE THREAD

**Issue by taz-chiles** [open-innovations/yff-data#82]
YFF would like to see this data going back further. Exact date TBC

**Comment by ODILMichelle** [comment]
Pre-requisites:

- [ ] Email Andrea, Zach & Chris to confirm a) exact starting date and b) whether it should be a rolling period of time or static start time. Probably makes sense to do this as part of #74

**Comment by ODILMichelle** [comment]
Asked about this as part of another email I sent - but we can follow up as part of #74 as well if there is no response.
