### ISSUE TITLE
Update vacancies pipeline to extract data from EDD

### ISSUE THREAD

**Issue by taz-chiles** [open-innovations/yff-data#86]
We currently pull datasets from a URL in our extract.py scripts forYFF economics pipelines, however this is fragile and unreliable. We should instead start to pull data from EDD - where Christian has kindly prepared the data in CSV format. 

Initially, we will look at pulling vacancies data in this way - with a view to updating other pipelines. 

- cd working directory
- Run dvc import -url with the following urls followed by the filename 

https://github.com/economic-analytics/edd/blob/main/data/csv/LMS_variable_lookup.csv

https://github.com/economic-analytics/edd/blob/main/data/csv/LMS_data.csv

This will download a ~.csv.dvc file into the working directory. This will be updated when the source updates and replaces the extract scripts we currently have in place. 

- Prepare the data in to the data direcory 
- Transform the data for visualisation from the data direclty into the src/_data directory.

**Comment by gilesdring** [comment]
I will take a look at this.

**Comment by gilesdring** [comment]
I WILL take a look at this!

**Comment by gilesdring** [comment]
Looks OK @taz-chiles - but make sure you have updated the `deps` and `outs` in the pipeline file!

I've made some alterations...

https://github.com/open-innovations/yff-data/commit/41a40add9f68f813950a947721587c544880d8b8
