### ISSUE TITLE
Tabs don’t work on ios / ipados safari

### ISSUE THREAD

**Issue by gilesdring** [open-innovations/yff-data#9]
Just noticed this evening. Have not checked desktop browsers. Will confirm in morning.

**Comment by gilesdring** [comment]
Can confirm works OK on Firefox / desktop platforms. Suspect it's a button not responding to touch events.

**Comment by gilesdring** [comment]
@slowe Could you take a look at this. I think it's in `src/assets/js/tabbed.js` and needs something to either set focus on a touch event or similar.

**Comment by slowe** [comment]
I checked it on an iPad and tabs now work.
