### ISSUE TITLE
Add headline figures for vacancy data

### ISSUE THREAD

**Issue by ODILMichelle** [open-innovations/yff-data#93]
Pre-reqs

- [ ] Agree with YFF what vacancy headline figures should be

**Comment by ODILMichelle** [comment]
Suggesting blocked until we have resolved #94

**Comment by ODILMichelle** [comment]
@taz-chiles Do you reckon we can make a stab at working out what these should or could be before we go into our next call with YFF?

**Comment by ODILMichelle** [comment]
First two certainly seem to make sense. I still remain a little unsure why we're showing growth on same quarter in 2020, vs say the last year. I know ONS do it, so it might be worth checking with Christian if there is a specific 'economics reason' to do this!

**Comment by taz-chiles** [comment]
I have added monthly and quarterly estimates in the interim, however need to query the vacancies data with @gilesdring tomorrow. The most recent stats we have are from Jan/Feb, so dvc is not refreshing the

**Comment by taz-chiles** [comment]
After a chat with Christian: 

- We can show either the monthly or quarterly estimated number of vacancies as a headline stat, both are valid (I had concerns about using the monthly stats) 
- We can also show the quarterly change, calculated from AP2Y

**Comment by ODILMichelle** [comment]
Thanks @taz-chiles. YFF previously asked for this to be quarterly - so perhaps we ensure we prioritise this, unless we have a good reason to recommend monthly instead. 

Is there a way to calculate this in England versus whole of UK?

**Comment by ODILMichelle** [comment]
Done

- [ ] Add language tweak in first headline stat - 'across the uk' or similar. @taz-chiles to explore if there are ways to show English figures. 
- [ ] Amend headline stats to be rolling 3 month period rather than quarterly. 


We will then need to get feedback from client about this - and flag that they had asked for quarterly, but we decided 3 monthly given that everything else on page is this!

**Comment by taz-chiles** [comment]
I've updated the vacancy headlines as above for now @ODILMichelle to review next wee

**Comment by ODILMichelle** [comment]
It says 'data TBC' in the Growth on previous quarter headline stat. 

Can this be amended quickly, or do we need a new ticket for it?

**Comment by taz-chiles** [comment]
I've added the date in now - this is the same date as the last quarterly release
