### ISSUE TITLE
Ensure we are adding youth context for vacancy data

### ISSUE THREAD

**Issue by ODILMichelle** [open-innovations/yff-data#94]
Pre-requisites

- [x] Ask YFF whether there are specific sectors we should be displaying, or whether word based context is appropriate.

**Comment by ODILMichelle** [comment]
What does done look like?

- [ ] Amend quarterly growth by sector visualisation to display Hospitality, Recreation & Retail (or the closely related names sectors)
- [ ] Add some description to top of box to say why we are focussing on these sectors (e.g. most youth focussed)
- [ ] Ensure YFF is aware of the fact the fact that we're displaying percentage growth from pre-coronavirus (COVID-19) pandemic January to March 2020 & that they are happy with this!

**Comment by ODILMichelle** [comment]
Gonna move this to ready if that's ok @taz-chiles?

**Comment by taz-chiles** [comment]
Yup, since I've already started looking at it, I'll move to in progress

**Comment by taz-chiles** [comment]
I have amended the visualisation. Categories were selected based on the [Large Employers and the Youth Labour Market Report](https://youthfuturesfoundation.org/wp-content/uploads/2021/10/Large-Employers-and-the-Youth-Labour-Market-report.pdf), using the following criteria. 

- Hospitality, Health and Social Care are key sectors for youth employment. 
- Manufacturing and Construction are growth industries i.e. green jobs. 
- Young people want to work in Creative, Professional and Financial Services industries. 
- Retail, Hospitality, Arts and Entertainment were particularly impacted by the coronavirus pandemic. 

However, in the latest release (May 2023), the Arts, entertainment and recreation sector is missing from the ONS data source. If this is rectified, then the visualisation will update to show the missing sector.

I have added a description with the above rationale that we can play back to YFF at next meeting.

**Comment by taz-chiles** [comment]
The names used in the description text above were the broad sector names used in the YFF report. The categories used in the visualisation are directly from the data source. They don't match up precisely, presumably because YFF were not strictly using the ONS category titles in this particular report. However, I have matched up the broad sectors to what I think is the closest match to the categories in the ONS data. I think it is sufficiently justified as to why we have included these categories, especially given the lastest ONS release is missing the Recreation sector. Thoughts?

**Comment by ODILMichelle** [comment]
When I looked at the pushed version I don't see any differences I think? Is it currently still local or am I missing something?

For instance, I can't see a 'hospitality' sector on the bar chart - but that may be a subset of one of the below sectors. Happy to chat if useful!

**Comment by ODILMichelle** [comment]
Hey @taz-chiles - as we discussed:

Lets create 3 tabs for the 'Quarterly growth by sector':

1. 'Key sectors for youth employment' - and show Hospitality, Recreation & Retail (and if you fancy is health & social care as it was in the report)
2. 'Key sectors young people want to work in' (or something snazzier/shorter) and pick up Creative, Professional and Financial Services industries.
3. All sectors - and put everything in there

**Comment by taz-chiles** [comment]
@ODILMichelle  I have added the above visualisations - still needs a couple of styling tweaks and to talk through but the data is there. 

https://data.youthfuturesfoundation.org/dashboard/vacancies/

**Comment by ODILMichelle** [comment]
Recognise it needs some re-sizing etc but that's being picked up via other tickets e.g. #181 

Need to get feedback fro YFF on whether this is useful. Had talked about need to get youth context displayed, but having issues with certain sectors apparently removed/not currently displaying in ONS data. This includes hospitality & recreation (which are key sectors YP work in) and creative industries (key sectors YP want to work in).
