### ISSUE TITLE
Ensure we are making it clear that QLFS data is seasonally adjusted

### ISSUE THREAD

**Issue by ODILMichelle** [open-innovations/yff-data#95]
Will likely need something saying this close to headline stats/in headline stats box & near visualisations where seasonal adjustments have taken place.

**Comment by ODILMichelle** [comment]
Also check whether NEET data needs this adding

**Comment by luke-strange** [comment]
@ODILMichelle

**Comment by ODILMichelle** [comment]
Do we include such information near the visualisations and headline stats as well? Just wondering as some people may skip over the text at the top?

**Comment by luke-strange** [comment]
Yes i will add that in
