### ISSUE TITLE
Publish interview with TFF key stakeholder about how YFF use data

### ISSUE THREAD

**Issue by ODILMichelle** [open-innovations/yff-data#97]
- [x] Determine key stakeholder
- [x] Arrange interview
- [x] Write up interview
- [x] Get write-up checked by YFF
- [x] Put on project site.

**Comment by ODILMichelle** [comment]
Drafted email to ask

**Comment by ODILMichelle** [comment]
Emailed to ask for this.

**Comment by taz-chiles** [comment]
Write-up from interview with Chris in progress, notes are here: https://docs.google.com/document/d/1y5hrL7k2kIiLT-KaYgwVZviCt9Z1PtD_c65IOvwiKAg/edit?usp=sharing

**Comment by taz-chiles** [comment]
First draft sent to Chris this afternoon - now with the client awaiting feedback before publishing next week
